// 32种跑步人格完整数据 — v4.2.5 PRD 第4章
// 5维编码: M(motivation) E(equipment=ritual) S(social) P(plan=style) X(expression)
// 左极: C=竞技 G=装备 L=独狼 P=计划 D=数据
// 右极: E=体验 M=极简 S=社群 S=随性 A=文艺
// 保留原16型数据作为fallback

import type { PersonalityCode, PersonalityResult, PersonalityTypeId } from './types';

/** 32型人格数据 */
const personalityData: Record<PersonalityCode, PersonalityResult> = {
  // ════════════════════════════════════════════════════════
  // TYPE 1 · CSGP_D · 精算赛道王 · 竞技×社群×计划×装备×数据
  // ════════════════════════════════════════════════════════
  'CSGP_D': {
    typeId: 1,
    code: 'CSGP_D',
    name: '精算赛道王',
    emoji: '🐆',
    keywords: ['PB焦虑症晚期', '数据教信徒', '路段KOM复仇者', '补给站过门不入', '课表执行率120%'],
    roast: '别人跑步为了健康，你跑步为了数据。Garmin少记了0.01公里你能难受一整天，Strava上有人抢了你的路段KOM你能记半年。你的生活是由间歇跑、节奏跑、LSD和「今天状态不好不跑了」构成的无限循环。每次跑完第一件事不是拉伸不是喝水，是掏出手机盯着配速曲线反复品味，像一个刚交卷的学霸在看成绩单。\n\n但你确实快。别人在补给站喝水，你已经在下一个弯道了。跑团的人提起你都说「那个从来不等人的」。等？开什么玩笑，等一秒配速掉两秒。你还负责跑团的数据记录——每个人的PB、配速趋势、心率区间变化，你比本人还清楚。',
    traits: ['每次跑完第一件事是看数据', '课表执行率比上班打卡还高', '跑团数据中心，记住所有人的PB'],
    dimensionScores: { motivation: -1, social: 1, style: -1, ritual: -1, expression: -1 },
    color: '#FF4444',
    colorFamily: 'warmred',
    colorTone: 'deep',
    quote: '等一秒配速掉两秒，掉两秒今天白跑。',
    colorDark: '#CC2222',
    svgIcon: 'CSGP',
    animalEmoji: '🐆',
    animalName: '猎豹',
    animalImg: '/runner-personality-h5/animals/animal-type-01.png',
    englishName: 'Cheetah',
    hook: '我跑步不是为了健康，是为了让昨天的自己无地自容。',
    dimensionComments: {
      motivation: '你跑的不是步，是跟自己较劲。昨天的自己是你永远的手下败将。',
      social: '跑团的数据中心+配速警察局。没你跑团也能跑，但没人分析数据了。',
      style: '训练课表比上班打卡还准时。缺一节间歇课罪恶感比旷工三天还强。',
      ritual: '鞋柜按碳板/竞速/训练/恢复四大类分区，每双鞋有里程记录。',
      expression: 'Strava是你的第二个朋友圈，每一公里都有数据信仰。',
    },
    shareTagline: '确诊为赛道卷王——数据是我的兴奋剂',
  },

  // ═══ TYPE 2 · CSGP_A · 出片赛道王 ═══
  'CSGP_A': {
    typeId: 2,
    code: 'CSGP_A',
    name: '出片赛道王',
    emoji: '🦚',
    keywords: ['数据美学化专家', '晒圈型PB选手', '配文比配速还稳定', '跑团合照C位终身制', '滤镜里的马拉松'],
    roast: '你练得比谁都狠，但你晒得比谁都精致。间歇跑完一组800米，你蹲在路边不是拉伸——是在构思今天的配文。「今天的汗水，是明天的勋章」这种句子在你脑子里是批量生产的。你拍完数据截图还要调色、加滤镜、选字体——跑步20分钟，修图半小时。\n\n但你不是在装。你只是觉得：既然跑了、拼了、PB了，凭什么不让它好看一点？成绩和审美对你来说是同一件事——跑得快还不够，要跑得漂亮、晒得精彩。跑团合照C位非你莫属，赛后九宫格永远点赞最高。',
    traits: ['PB和出片率双冠王', '跑步20分钟修图半小时', '跑团合照永远的C位'],
    dimensionScores: { motivation: -1, social: 1, style: -1, ritual: -1, expression: 1 },
    color: '#E91E63',
    colorFamily: 'warmred',
    colorTone: 'bright',
    quote: 'PB很重要，但PB的截图能不能发朋友圈更重要。',
    colorDark: '#AD1457',
    svgIcon: 'CSGA',
    animalEmoji: '🦚',
    animalName: '孔雀',
    animalImg: '/runner-personality-h5/animals/animal-type-02.png',
    englishName: 'Peacock',
    hook: 'PB很重要，但PB的截图能不能发朋友圈更重要。',
    dimensionComments: {
      motivation: '快是底线，好看是追求。二者兼得才是你。',
      social: '跑团的精神图腾——冲线照、集体照、奖牌照，全出自你手。',
      style: '课表执行严格，但每完成一项都要拍照存档——这是仪式感。',
      ritual: '跑鞋的配色必须和今天的穿搭呼应。跑得快的人更有资格讲究。',
      expression: '每一步都在创造内容。你不是在跑步，你是在拍运动纪录片。',
    },
    shareTagline: 'PB和出片率双冠王',
  },

  // ═══ TYPE 3 · CGSS_D · 炸鱼特种兵 ═══
  'CGSS_D': {
    typeId: 3,
    code: 'CGSS_D',
    name: '炸鱼特种兵',
    emoji: '🦈',
    keywords: ['Deadline型爆种选手', '间歇跑社恐制造者', '配速坐过山车选手', '赛前两周变身机器人', '队友配速心理阴影来源'],
    roast: '平时训练主打一个随缘——今天心情好就跑，心情不好也跑。赛前两周突然变身精密训练机器，所有数据精确到秒。跑团的人对你的印象是「那个间歇跑冲到前面然后消失的人」。你的间歇配速让队友怀疑人生，但你从不解释——数据就是最好的语言。\n\n你不是不想跟大家一起训练，是你的节奏太野了。周一还在慢摇7分配，周三就间歇冲3分半。没人能跟上你的节奏切换，所以你跟谁跑都像在独跑——只是碰巧在同一个跑团。',
    traits: ['赛前两周突然变身机器人', '间歇配速让队友怀疑人生', '平时佛系赛前暴走'],
    dimensionScores: { motivation: -1, social: 1, style: 1, ritual: -1, expression: -1 },
    color: '#FF6B35',
    colorFamily: 'warmred',
    colorTone: 'deep',
    quote: '平时你看不见他练，比赛日你看不见他尾灯。',
    colorDark: '#CC4400',
    svgIcon: 'CGSD',
    animalEmoji: '🦈',
    animalName: '虎鲨',
    animalImg: '/runner-personality-h5/animals/animal-type-03.png',
    englishName: 'Tiger Shark',
    hook: '平时你看不见他练，比赛日你看不见他尾灯。',
    dimensionComments: {
      motivation: '平时佛系、赛前暴走——Deadline是你的第一生产力。',
      social: '间歇跑永远冲在最前面——跑完还要加两组，队友在心里集体翻白眼。',
      style: '训练看心情，但赛前两周突然变成精密仪器——反差是最大的恐怖。',
      ritual: '装备必须顶配——「哪个能帮我PB就买哪个」，不买最好的只买最快的。',
      expression: '赛前所有数据精确到秒；赛后的数据分析比比赛本身还长。',
    },
    shareTagline: '平时佛系，赛前暴走——别被我骗了',
  },

  // ═══ TYPE 4 · CGSS_A · 花式特种兵 ═══
  'CGSS_A': {
    typeId: 4,
    code: 'CGSS_A',
    name: '花式特种兵',
    emoji: '🪶',
    keywords: ['天赋型博主', '穿搭配速双修', '赛后九宫格秒出', '间歇跑痛苦面具艺术家', '比赛日穿搭设计师'],
    roast: '你是跑团里最分裂的存在：训练随性得让教练头疼，但一到比赛就全身装备拉满，配色精心搭配，像从跑步杂志封面走出来的。别人研究配速策略你在研究起跑线穿搭，别人算补给时间你在算哪个弯道光线最好——然后你跑得还贼快。\n\n队友对你的感情很复杂：又爱你的热闹，又恨你「明明没怎么练为什么还这么快」。赛后你的九宫格出片速度跟你的配速一样快，别人还没拉伸完，你的朋友圈已经30个赞了。',
    traits: ['天赋型卷王不用刻苦但比赛从不掉链子', '赛后九宫格出片速度=配速', '比赛日穿搭比训练还认真'],
    dimensionScores: { motivation: -1, social: 1, style: 1, ritual: -1, expression: 1 },
    color: '#9C27B0',
    colorFamily: 'warmred',
    colorTone: 'bright',
    quote: '间歇跑完发一张痛苦面具自拍——这才是完整的训练。',
    colorDark: '#6A1B9A',
    svgIcon: 'CGSA',
    animalEmoji: '🪶',
    animalName: '极乐鸟',
    animalImg: '/runner-personality-h5/animals/animal-type-04.png',
    englishName: 'Bird of Paradise',
    hook: '间歇跑完发一张痛苦面具自拍——这才是完整的训练。',
    dimensionComments: {
      motivation: '天赋型卷王——不用刻苦训练但比赛从不掉链子。',
      social: '跑团的气氛引擎——你在哪热闹就在哪。',
      style: '训练？看心情。比赛？全副武装。日常？看有没有人约。',
      ritual: '比赛日的装备是一套完整的视觉系统。配色/层次/品牌搭配——赛前准备比训练还认真。',
      expression: '赛后的朋友圈是一场小型展览。痛苦面具+冲刺瞬间+奖牌特写=三件套。',
    },
    shareTagline: '穿搭型竞速选手——快且好看',
  },

  // ═══ TYPE 5 · CGLP_D · 暗影破风者 ═══
  'CGLP_D': {
    typeId: 5,
    code: 'CGLP_D',
    name: '暗影破风者',
    emoji: '🐆',
    keywords: ['潜水型站台选手', '课表隐身执行者', '数据沉默主义', '只见背影不见人', '低调炫技大师'],
    roast: '跑团群永远潜水，朋友圈从不开张，但手表/App数据是公开的——而且全在PR。他不解释不争辩不打卡不晒图，但每次比赛站台名单上都有他。训练计划写在备忘录里，课表完成率接近100%，但绝不让你知道。你以为他不跑，其实他在你没看见的时候跑了三个全马。\n\n装备精良但不炫耀——每一双鞋的选择都基于配速数据和脚感测试。他不分享不是因为冷漠，是因为觉得数据本身就是最好的表达。你问他「怎么这么快」，他说「多跑就行」——简洁、精确、无法反驳。',
    traits: ['课表完成率100%但绝不让你知道', '每双鞋的选择基于数据分析', '「多跑就行」——简洁精确无法反驳'],
    dimensionScores: { motivation: -1, social: -1, style: -1, ritual: -1, expression: -1 },
    color: '#607D8B',
    colorFamily: 'warmred',
    colorTone: 'deep',
    quote: '你永远不知道他有多快，因为他从不说。但数据知道。',
    colorDark: '#37474F',
    svgIcon: 'CGLD',
    animalEmoji: '🐆',
    animalName: '黑豹',
    animalImg: '/runner-personality-h5/animals/animal-type-05.png',
    englishName: 'Black Panther',
    hook: '你永远不知道他有多快，因为他从不说。但数据知道。',
    dimensionComments: {
      motivation: '低调是最狠的炫耀。嘴上说「随便跑」，脚下配速从不说谎。',
      social: '一个人训练、一个人比赛、一个人回家。只留下一地传说的配速数据。',
      style: '课表执行率100%，但课表本身不对任何人公开。',
      ritual: '每一双鞋都是经过数据分析后的选择——科学买鞋，精准退役。',
      expression: 'Strava公开数据是他的唯一社交语言。数字比文字诚实。',
    },
    shareTagline: '沉默是金，配速是钻，数据是真相',
  },

  // ═══ TYPE 6 · CGLP_A · 孤风诗人 ═══
  'CGLP_A': {
    typeId: 6,
    code: 'CGLP_A',
    name: '孤风诗人',
    emoji: '🕊️',
    keywords: ['沉默的跑者诗人', '跑道上的隐士', '复购型装备哲学', '配速如诗', '不存在的朋友圈'],
    roast: '他不说话，但他的跑姿在说话；他不发朋友圈，但他的冲线照片在被别人发。训练极其自律，课表完成率接近100%——但他从来不晒，因为跑步对他来说是「只属于自己的叙事」。一篇没人看的长文、一首只唱给自己听的歌。\n\n装备精致但统一：同一型号的跑鞋连买三双，因为「磨合太麻烦」。路线固定、时间固定、配速固定——像一段反复演奏却从不腻的旋律。他不是没有表达欲，他只是把表达放在了每一步里。',
    traits: ['同一型号跑鞋无限复购', '跑步是只属于自己的叙事', '固定时间固定路线固定配速'],
    dimensionScores: { motivation: -1, social: -1, style: -1, ritual: -1, expression: 1 },
    color: '#3F51B5',
    colorFamily: 'warmred',
    colorTone: 'bright',
    quote: '不晒图不约跑不换鞋——但每次冲线照片里，他的眼神都像在写一首诗。',
    colorDark: '#1A237E',
    svgIcon: 'CGLA',
    animalEmoji: '🕊️',
    animalName: '丹顶鹤',
    animalImg: '/runner-personality-h5/animals/animal-type-06.png',
    englishName: 'Red-crowned Crane',
    hook: '不晒图不约跑不换鞋——但每次冲线照片里，他的眼神都像在写一首诗。',
    dimensionComments: {
      motivation: '实力是最好的表达。不说话不是冷漠，是觉得没必要。',
      social: '像武侠小说里独来独往的高手——只留下一地传说的配速和偶尔被偷拍的背影。',
      style: '固定的时间、固定的路线、固定的配速——重复即是修行。',
      ritual: '装备精良但统一——找到了对的鞋就无限复购，审美和功能一样稳定。',
      expression: '不晒图、不码字，但每一步都在书写自己的跑步史诗。只是没人读到。',
    },
    shareTagline: '他不在朋友圈跑步，但每一步都是朋友圈级别的存在',
  },

  // ═══ TYPE 7 · CGLS_D · 鞋狗研究员 ═══
  'CGLS_D': {
    typeId: 7,
    code: 'CGLS_D',
    name: '鞋狗研究员',
    emoji: '🐝',
    keywords: ['跑鞋证券分析师', '中底回弹率研究员', '鞋墙资产管理人', '3公里测评博主', '装备复购率永远大于消耗率'],
    roast: '你的购物车比月跑量长，但每一件装备你都能说出三个买它的技术理由。对每双鞋的中底科技如数家珍，回弹率/能量反馈/前后掌落差——这些参数对你来说是「基础知识」。你的跑鞋评测比品牌官方详细，数据分析维度比你公司的财务报表还多。\n\n问题是：买鞋的速度远超消耗鞋的速度。鞋墙一直在扩张，像个永远在融资的创业公司。但你不在乎——每双鞋都是你跑者身份的一部分，是你对跑步的「数据化热爱」。',
    traits: ['用读论文的方法买跑鞋', '跑鞋评测比品牌官方还详细', '鞋墙扩张速度远超跑步消耗'],
    dimensionScores: { motivation: -1, social: -1, style: 1, ritual: -1, expression: -1 },
    color: '#7B1FA2',
    colorFamily: 'warmred',
    colorTone: 'deep',
    quote: '跑鞋比股票涨得好——至少你能穿它跑步。',
    colorDark: '#4A148C',
    svgIcon: 'CGLS',
    animalEmoji: '🐝',
    animalName: '蜜蜂',
    animalImg: '/runner-personality-h5/animals/animal-type-07.png',
    englishName: 'Bee',
    hook: '跑鞋比股票涨得好——至少你能穿它跑步。',
    dimensionComments: {
      motivation: '装备是手段不是目的——但你把手段研究成了另一种目的。',
      social: '一个人买、一个人试、一个人写测评——你的数据世界不需要别人的意见。',
      style: '训练看心情，但装备不含糊——今天的配色必须配得上今天的天气。',
      ritual: '中底回弹率、能量反馈率、碳板刚性——你用读论文的方法买跑鞋。',
      expression: '每双鞋有里程记录、配速变化、退役评估——这是一个跑鞋数据库。',
    },
    shareTagline: '我不是在买装备，我是在做跑步实证研究',
  },

  // ═══ TYPE 8 · CGLS_A · 鞋柜收藏家 ═══
  'CGLS_A': {
    typeId: 8,
    code: 'CGLS_A',
    name: '鞋柜收藏家',
    emoji: '🪺',
    keywords: ['跑鞋叙事诗人', '开箱仪式感大师', '3公里故事创造者', '鞋墙回忆录作者', '脚感散文专业户'],
    roast: '你买装备不是为了数据，是为了「感受」。新款碳板上脚那一刻的感觉——像第一次听一首好歌、像翻开一本新书的第一页。开箱对你来说是一场小型仪式：剪开塑封、拿出鞋、凑近闻一下新鞋的味道、在阳光下转一圈看配色——然后穿上跑3公里，回来写一段200字的「脚感散文」。\n\n你的鞋墙是一本立体日记。每一双鞋都对应一段跑步记忆：「这双陪我跑过东京的雨」「这双见证了我第一次跑进5分配」。你不卖鞋，你收集故事。',
    traits: ['开箱仪式感堪比马拉松起跑线', '每双鞋配一段跑步记忆', '鞋墙=立体日记本'],
    dimensionScores: { motivation: -1, social: -1, style: 1, ritual: -1, expression: 1 },
    color: '#E040FB',
    colorFamily: 'warmred',
    colorTone: 'bright',
    quote: '每一双鞋都有一个故事——虽然有的故事只有3公里长。',
    colorDark: '#7B1FA2',
    svgIcon: 'CGLA',
    animalEmoji: '🪺',
    animalName: '园丁鸟',
    animalImg: '/runner-personality-h5/animals/animal-type-08.png',
    englishName: 'Bowerbird',
    hook: '每一双鞋都有一个故事——虽然有的故事只有3公里长。',
    dimensionComments: {
      motivation: '快很重要，但快的「感觉」更重要——而这只有你能描述。',
      social: '买鞋和跑步都是一个人的仪式。不需要别人的意见，因为感受是主观的。',
      style: '今天跑不跑取决于今天快递到没到——新鞋到了就跑，没到就等鞋到了再跑。',
      ritual: '鞋墙=跑步日记。每双鞋不是装备，是记忆的实体化。',
      expression: '每一篇开箱笔记都是一首写给跑鞋的情诗。只不过受众只有你一个人。',
    },
    shareTagline: '我买的不是鞋，是跑步生活的每一个可能',
  },

  // ═══ TYPE 9 · CMSP_D · 数据大管家 ═══
  'CMSP_D': {
    typeId: 9,
    code: 'CMSP_D',
    name: '数据大管家',
    emoji: '🐘',
    keywords: ['人形跑团数据库', 'Excel马拉松选手', '配速HR总监', '义务劳动终身成就奖', '谁的PB都记得——除了自己的'],
    roast: '你是跑团的移动数据库+人事总监+赛历管家，三合一体。别人跑步带能量胶，你跑步带的是每个人的训练档案——「小李上周偷懒了两天，今天该安排个间歇唤醒一下」。一双跑鞋穿到磨穿、一块手表用到停产——你的装备投资是负数，但你在数据和人情上的投资是天文数字。\n\n跑团几十号人，你比每个人自己都清楚他们：谁上月配速掉了5秒、谁膝盖老伤该换康复动作了、谁偷偷报了比赛没告诉大家。你不是团长——但团长做任何决定之前，不看天气预报，先看你。',
    traits: ['记得全团每个人的PB和伤病史', '一双鞋穿到磨穿不换', '团长做决定前先看你'],
    dimensionScores: { motivation: -1, social: 1, style: -1, ritual: 1, expression: -1 },
    color: '#2196F3',
    colorFamily: 'warmred',
    colorTone: 'deep',
    quote: '跑团的数据中枢——团长管人，你管Excel。',
    colorDark: '#0D47A1',
    svgIcon: 'CMSD',
    animalEmoji: '🐘',
    animalName: '大象',
    animalImg: '/runner-personality-h5/animals/animal-type-09.png',
    englishName: 'Elephant',
    hook: '跑团的数据中枢——团长管人，你管Excel。哪天你请假，跑完的群聊只剩「今天天气不错」。',
    dimensionComments: {
      motivation: '你的竞技场不在赛道上——在你的Excel里。每一行数据都是你的完赛奖牌。',
      social: '你是跑团的人形数据库。查询「谁最近状态好」比Garmin的搜索还快。',
      style: '你的训练计划精确到秒——但更可怕的是，全团的训练计划你也在管。',
      ritual: '一双鞋穿到退役不是抠——是每双鞋的公里数你都有记录，没跑够舍不得换。',
      expression: 'Excel是你最趁手的跑步装备。一双跑鞋陪你几百公里，一张表格陪你到退役。',
    },
    shareTagline: '跑团首席数据官——查成绩找我，查天气不归我管',
  },

  // ═══ TYPE 10 · CMSP_A · 跑团聚心人 ═══
  'CMSP_A': {
    typeId: 10,
    code: 'CMSP_A',
    name: '跑团聚心人',
    emoji: '🐺',
    keywords: ['跑团记忆银行', '赛后长文型总结官', '全团PB守望者', '极简装备·丰盛灵魂', '跑团人类学家'],
    roast: '你是跑团的情感档案馆。别人的Strava记录配速和心率，你的大脑记录的是「小张在那个补给站哭了」「老李在35公里处突然笑了」「阿花第一次跑完半马抱着奖牌睡了一晚」。你的个人PB从来不是重点——你追求的KPI是「全团都在、全团都开心」。\n\n装备极简到一双鞋穿三年，但你对队友的关心三年如一日地浓烈。每次约跑前你已经踩好了路线、查好了天气、甚至看好了停车场——你组织的不是跑步，是一场精密策划的小型团圆。赛后你不发数据截图，你写长文：不是总结配速，是给每个人写一段人物小传。',
    traits: ['记得谁在哪场比赛哭过笑过', '一双鞋穿三年关心队友三年', '赛后写人物小传不写配速总结'],
    dimensionScores: { motivation: -1, social: 1, style: -1, ritual: 1, expression: 1 },
    color: '#00BCD4',
    colorFamily: 'warmred',
    colorTone: 'bright',
    quote: '你记不住自己跑过多少次PB——但你记得每个人在哪场比赛中哭过、笑过。',
    colorDark: '#006064',
    svgIcon: 'CMSA',
    animalEmoji: '🐺',
    animalName: '狼',
    animalImg: '/runner-personality-h5/animals/animal-type-10.png',
    englishName: 'Wolf',
    hook: '你记不住自己跑过多少次PB——但你记得每个人在哪场比赛中哭过、笑过、想过放弃，然后坚持到了终点。',
    dimensionComments: {
      motivation: '别人的PB是你的多巴胺。看队友冲线比自己冲线还激动——手抖得对不了焦。',
      social: '你是跑团的情感中枢。谁低落、谁兴奋、谁需要被推一把——你比任何App都灵敏。',
      style: '你计划的不是训练课表——是每一次聚会的温度。路线、补给、合影位、饭后甜品，全部到位。',
      ritual: '一双跑鞋穿到磨穿底——因为你的预算都留给了约跑后的那顿团圆饭。',
      expression: '赛后总结=跑团人物群像。你不写配速数据，你写「今天谁笑了，谁又突破了自己」。',
    },
    shareTagline: '我是跑团的记忆——不是数据，是一本还在写的故事书',
  },

  // ═══ TYPE 11 · CMSS_D · 赤脚数据狂 ═══
  'CMSS_D': {
    typeId: 11,
    code: 'CMSS_D',
    name: '赤脚数据狂',
    emoji: '🐎',
    keywords: ['扫地僧跑者', '旧T恤杀手', '配速拆解狂魔', '装备党的心理阴影', '数据比装备贵一百倍'],
    roast: '你看上去不像跑者——松垮旧T恤、看不出牌子的跑鞋、从来没聊过碳板和能量胶。但哨声一响，你像被按下开关：配速比秒表还稳、心率曲线比教科书还平、步频精准得像节拍器。跑团的人给你起了外号叫「扫地僧」——穿得最随便的那个，永远在把你拉爆。\n\n群聊里你是数据分析担当：别人讨论哪双鞋好看，你在发配速拆解图；别人晒新装备开箱，你在晒心率区间分布统计。你最享受的瞬间不是PB——是穿着旧T恤超过全套压缩衣的装备党时，他们脸上那种「那我购物车白清了？」的表情。',
    traits: ['旧T恤+磨平底的鞋=最快配速', '群聊里只发数据不晒装备', '装备党的心理阴影制造者'],
    dimensionScores: { motivation: -1, social: 1, style: 1, ritual: 1, expression: -1 },
    color: '#FF9800',
    colorFamily: 'warmred',
    colorTone: 'deep',
    quote: '旧T恤、磨平底的鞋、从不聊装备——但你起跑后，装备党集体沉默了。',
    colorDark: '#E65100',
    svgIcon: 'CMSD',
    animalEmoji: '🐎',
    animalName: '野马',
    animalImg: '/runner-personality-h5/animals/animal-type-11.png',
    englishName: 'Mustang',
    hook: '旧T恤、磨平底的鞋、从不聊装备——但你起跑后，装备党集体沉默了。反差，是最恐怖的武器。',
    dimensionComments: {
      motivation: '旧T恤是你的战袍，碳板鞋是对手的拐杖。你靠的不是装备——是实力。',
      social: '群聊=你的数据分析发布会。别人晒装备，你晒配速拆解——降维打击。',
      style: '出门就跑——不挑时间、不挑衣服、不挑路线。但数据永远一丝不苟。',
      ritual: '鞋=磨平底，T恤=三年前的款。但每次起跑后，装备党队友就开始反思自己的购物车。',
      expression: '你的快乐不是新鞋上脚——是配速曲线比上次又平滑了0.3秒每公里。',
    },
    shareTagline: '装备极简，数据极繁——反差型降维打击选手',
  },

  // ═══ TYPE 12 · CMSS_A · 跑团开心果 ═══
  'CMSS_A': {
    typeId: 12,
    code: 'CMSS_A',
    name: '跑团开心果',
    emoji: '🦦',
    keywords: ['跑团气氛永动机', '跑后早餐首席推荐官', '500米冲刺限定选手', '群聊段子手·终身制', '出勤率即统治力'],
    roast: '你是跑团唯一的非正式KPI——群聊活跃度。约跑从不迟到、跑完从不早退——因为跑完那顿早饭才是你的主舞台。你不纠结间歇配速、不研究心率区间、不关心碳板还是尼龙板——你关心的是「这家肠粉配不配得上我们刚才跑的8公里」。\n\n训练看心情、装备看手边。但有人喊「最后500米冲刺」时，你是全场第一个飞出去的人。冲完线立刻切回佛系模式：「刚才谁喊冲刺的？赶紧找地方吃早饭。」跑团有你=有笑声、有聚餐、有段子。跑团没你=一群人闷头跑完默默解散。',
    traits: ['约跑从不迟到跑完从不早退', '跑完那顿早饭才是主舞台', '喊冲刺第一个飞出去'],
    dimensionScores: { motivation: -1, social: 1, style: 1, ritual: 1, expression: 1 },
    color: '#FFC107',
    colorFamily: 'warmred',
    colorTone: 'bright',
    quote: '跑团如果没有你——配速不会变慢，但笑声会少一半。',
    colorDark: '#FF8F00',
    svgIcon: 'CMSA',
    animalEmoji: '🦦',
    animalName: '水獭',
    animalImg: '/runner-personality-h5/animals/animal-type-12.png',
    englishName: 'Otter',
    hook: '跑团如果没有你——配速不会变慢，但笑声会少一半。你是跑团的背景音乐，配速随便，快乐必达。',
    dimensionComments: {
      motivation: '竞技的快乐只有500米——从喊「冲刺」到冲线。剩下时间交给社交和碳水。',
      social: '出勤率冠军、笑声分贝冠军、跑后聚餐选址冠军——三项全能，全是民选。',
      style: '计划？不存在。群里有人喊就跑，没人喊就等有人喊。',
      ritual: '有双鞋就行。你的核心装备不是跑鞋——是跑完那顿饭的推荐能力。',
      expression: '你用段子写跑团编年史。每一条群聊都是本周的笑点合集——收藏比配速截图还多。',
    },
    shareTagline: '跑团快乐引擎——唯一KPI是笑声分贝',
  },

  // ═══ TYPE 13 · CMLP_D · 数据修行者 ═══
  'CMLP_D': {
    typeId: 13,
    code: 'CMLP_D',
    name: '数据修行者',
    emoji: '🦉',
    keywords: ['数据修行者', '配速禅修中心', '固定路线信仰者', '心率冥想家', '一个人的完美闭环'],
    roast: '你的跑步不需要观众。同一条路跑了两年半，路边的树都认识你了——但你从不在意这些。你在意的是今天的配速波动比昨天小了0.2秒、心率恢复快了3秒、步频稳定性比上周提升了。你不是在跑步——你是在用身体做数字冥想。\n\n极简到极致：没有耳机（音乐会干扰心率感知）、没有跑友（聊天会打断配速节奏）、甚至没有表情（专注到面瘫）。手表是你唯一的装备——但这不是工具，是禅修法器。朋友圈从不发跑步内容，但你的云盘里存着两年多的训练数据，每一组间歇后面都有一段手写笔记。',
    traits: ['同一条路跑了两年半不换', '手表是禅修法器不是工具', '每一组间歇后手写笔记'],
    dimensionScores: { motivation: -1, social: -1, style: -1, ritual: 1, expression: -1 },
    color: '#2c3e80',
    colorFamily: 'warmred',
    colorTone: 'deep',
    quote: '固定路线、固定时间、固定配速——你以为他在重复，他其实在修行。',
    colorDark: '#1a237e',
    svgIcon: 'CMLD',
    animalEmoji: '🦉',
    animalName: '猫头鹰',
    animalImg: '/runner-personality-h5/animals/animal-type-13.png',
    englishName: 'Owl',
    hook: '固定路线、固定时间、固定配速——你以为他在重复，他其实在修行。手表是他的念珠，数据是他的经文。',
    dimensionComments: {
      motivation: '对手不是别人——是昨天的配速曲线、上周的心率趋势、上个月的步频稳定度。',
      social: '一个人的固定路线。不是不想约人——是怕聊天的节奏打乱了配速的节奏。',
      style: '每周三次，雷打不动——不是自律上瘾，是需要确定的秩序感来平衡世界的混乱。',
      ritual: '手表是你唯一的奢侈。鞋=消耗品，表=修行入口——其他都是干扰信号。',
      expression: '数据不是用来炫耀的——是用来对话的。每一个数字都是身体的一次呼吸。',
    },
    shareTagline: '我的跑步是数据冥想——一个人的无限循环',
  },

  // ═══ TYPE 14 · CMLP_A · 跑道沉思者 ═══
  'CMLP_A': {
    typeId: 14,
    code: 'CMLP_A',
    name: '跑道沉思者',
    emoji: '🦌',
    keywords: ['跑道沉思者', '固定路线的哲学家', '独处艺术家', '沉默的跑者', '在路上遇见自己'],
    roast: '你的跑步不需要目的地——因为你的目的地是「想清楚」。固定的路线、固定的时间——但每一次都像第一次：今天的梧桐叶比昨天黄了一个色号、今天下午四点十七分的光线刚好穿过那棵银杏、今天路过第三个弯道时风里有桂花味。你观察的不是配速——是季节的流转和时间的纹理。\n\n不听歌（音乐太吵）、不看表（数据太刺眼）、不约人（社交太累）——你只有一双鞋、一条路、一个无人打扰的自我。跑步是你一天中唯一完全属于自己的时间——不是锻炼，是放空；不是逃离，是回家。',
    traits: ['同一条路跑了三年观察季节变化', '跑步时不听歌不看表不约人', '跑步是放空是回家'],
    dimensionScores: { motivation: -1, social: -1, style: -1, ritual: 1, expression: 1 },
    color: '#795548',
    colorFamily: 'warmred',
    colorTone: 'bright',
    quote: '同一条路跑了三年——不是懒，是这条路刚好够思考人生所有重要的事。',
    colorDark: '#4E342E',
    svgIcon: 'CMLA',
    animalEmoji: '🦌',
    animalName: '鹿',
    animalImg: '/runner-personality-h5/animals/animal-type-14.png',
    englishName: 'Deer',
    hook: '同一条路跑了三年——不是懒，是这条路刚好够思考人生所有重要的事。跑完就放下了，或者跑完就想通了。',
    dimensionComments: {
      motivation: '你的竞速是和时间的流逝比赛——跑到想清楚为止，而不是跑到某个配速。',
      social: '独处是选择，不是孤独。你的内心世界很满——满到不需要再加一个人进来。',
      style: '固定时间+固定路线=你给生活下的锚。锚在，世界再乱你也不怕。',
      ritual: '一双鞋、一条路、一个人。全部家当都在这里——但你觉得富可敌国。',
      expression: '同一棵树看了三年——但每一年、每一个季节、每一次路过，它都是新的。',
    },
    shareTagline: '我在同一条路上跑了三年——还没跑到头，因为路会生长',
  },

  // ═══ TYPE 15 · CMLS_D · 野路子数据师 ═══
  'CMLS_D': {
    typeId: 15,
    code: 'CMLS_D',
    name: '野路子数据师',
    emoji: '🦊',
    keywords: ['野路子数据师', '天赋碾压受害者联盟', '手表电量永远1%', '凡尔赛跑者', '不练传说制造者'],
    roast: '这类人的存在是对跑圈知识体系的降维打击。别人翻论文研究训练周期、配速分区、心率区间管理——他穿一双旧鞋出门，不热身、不拉伸、不戴心率带，然后跑出你苦练三个月的配速。你问他训练心得，他说「没啥，跑就完了」。你问他补给策略，他说「渴了喝水」。你问他到底是怎么做到的——他看看手表：「噢，刚才忘了开Strava」。\n\n最气人的不是他快——是他明明有天赋和数据，却从来不好好利用。手表常年1%电量、Strava密码忘了、训练记录靠脑子记——但偶尔翻出那几条存下来的数据，每一条都是教科书级别的配速曲线。',
    traits: ['不热身不拉伸跑出你苦练的配速', '手表常年1%电量', '偶尔记录的数据条条都是教科书'],
    dimensionScores: { motivation: -1, social: -1, style: 1, ritual: 1, expression: -1 },
    color: '#4CAF50',
    colorFamily: 'warmred',
    colorTone: 'deep',
    quote: '月跑量不到80K，半马轻松145。天赋，从不讲道理。',
    colorDark: '#2E7D32',
    svgIcon: 'CMLD',
    animalEmoji: '🦊',
    animalName: '狐',
    animalImg: '/runner-personality-h5/animals/animal-type-15.png',
    englishName: 'Fox',
    hook: '月跑量不到80K，半马轻松145。他的数据是对「科学训练」的最大嘲讽——天赋，从不讲道理。',
    dimensionComments: {
      motivation: '天赋是他的出厂设置。你苦练三个月，是在追一个他天生就有的数据。',
      social: '一个人跑、一个人PB、一个人消失——然后突然用一条数据打脸所有人的训练计划。',
      style: '训练计划？不需要。饮食管理？不存在。但他的数据比你的训练笔记还漂亮——气不气？',
      ritual: '不买装备不是穷——是他真心觉得你快不起来，跟鞋没关系。',
      expression: '他的数据像未解之谜——偶尔记录一次就能炸翻跑团群。但他自己完全不知道。',
    },
    shareTagline: '天赋教信徒——训练是你们的，速度是他的',
  },

  // ═══ TYPE 16 · CMLS_A · 天生跑者 ═══
  'CMLS_A': {
    typeId: 16,
    code: 'CMLS_A',
    name: '天生跑者',
    emoji: '🦌',
    keywords: ['天生跑者', '不晒数据只晒风景', '猫科跑者·优雅即正义', '不费力的天赋', '松弛感PB体质'],
    roast: '天赋型文艺派是跑圈最让人羡慕又最让人牙痒的存在。他跑步的样子像猫——优雅、轻松、不讲道理。配速快得像在飞，但你看他的表情——他在感受风吹过脸的触感，而不是在做「训练」。他从不发配速截图——但偶尔会发一张晨跑时拍的日出：「今天路过的时候刚好升起来，好看。」\n\n你的Strava充满间歇跑、节奏跑、LSD的精密数据，他的朋友圈只有花、云、晨光和一条空荡的跑道。你不确定他是在跑步还是在散步——但每次比赛他的名字都在你前面。最让你崩溃的真相是：他从来没把你当对手。',
    traits: ['跑步像猫一样优雅轻松', '朋友圈只有花云晨光没有配速', '从来没把你当对手'],
    dimensionScores: { motivation: -1, social: -1, style: 1, ritual: 1, expression: 1 },
    color: '#8BC34A',
    colorFamily: 'warmred',
    colorTone: 'bright',
    quote: '他不练、不卷、不晒——但你就是跑不过他。他甚至没在跟你比。',
    colorDark: '#558B2F',
    svgIcon: 'CMLA',
    animalEmoji: '🦌',
    animalName: '羚羊',
    animalImg: '/runner-personality-h5/animals/animal-type-16.png',
    englishName: 'Gazelle',
    hook: '他不练、不卷、不晒——但你就是跑不过他。最让你崩溃的是：他甚至没在跟你比。他的快乐是真的，你的焦虑是你自找的。',
    dimensionComments: {
      motivation: '快不是他追求的——是他自然的配速。就像呼吸——不需要努力，天生就会。',
      social: '一个人的奔跑——不等人、不追人、不比较。他只是和自己的影子赛跑。',
      style: '今天跑不跑看心情——跑起来看风景。但无论心情好坏，配速从不掉线。',
      ritual: '穿什么都快。你借他拖鞋他可能都能跑出5分配——别试，试了你更难受。',
      expression: '他的成绩单不是配速——是路上的日出、树梢的风、和跑完那杯恰好烫口的豆浆。',
    },
    shareTagline: '跑得快是天生的，跑得快乐是选择的——他两项都做到了',
  },

  // ═══ TYPE 17 · EGSP_D · 慢摇装备党 ═══
  'EGSP_D': {
    typeId: 17,
    code: 'EGSP_D',
    name: '慢摇装备党',
    emoji: '🦥',
    keywords: ['慢摇界装备天花板', '六分半气氛组', '约跑=移动茶话会', '路线以奶茶店为坐标', '装备党中最松弛的存在'],
    roast: '你全身上下装备拉满——压缩袜、心率带、最新款碳板，路人看了以为你是破3大神。结果一抬腿，六分半，还在回头问「你们刚才看到那只柯基了吗」。但你说得太对了：穿最好的装备跑最开心的步，有什么问题？你为跑团做的计划比训练计划详细三倍——补给站定位精确到拍照角度，路线规划以「沿途有几家奶茶店」为核心指标。数据你也看，但数据对你来说就像天气预报——知道了就行，不影响心情。',
    traits: ['碳板鞋配六分半配速', '路线规划以奶茶店为坐标', '数据看了不焦虑'],
    dimensionScores: { motivation: 1, social: 1, style: -1, ritual: -1, expression: -1 },
    color: '#27ae60',
    colorFamily: 'forest',
    colorTone: 'deep',
    quote: '碳板鞋配六分半配速——不是跑不快，是跑快了谁陪你聊天啊。',
    colorDark: '#1e8449',
    svgIcon: 'EGSD',
    animalEmoji: '🦥',
    animalName: '树懒',
    animalImg: '/runner-personality-h5/animals/animal-type-17.png',
    englishName: 'Sloth',
    hook: '碳板鞋配六分半配速——不是跑不快，是跑快了谁陪你聊天啊。',
    dimensionComments: {
      motivation: '跑步的KPI不是配速——是「今天开心吗」「聊够了吗」「那张合影光线好不好」。',
      social: '约跑出勤率100%——不是因为自律，是因为不想错过任何一次八卦和笑声。',
      style: '你的计划表=路线+拍照点+奶茶店+聚餐位。配速？最后一个单元格，经常空着。',
      ritual: '六分配也要穿碳板——不是装，是「既然跑了，凭什么不穿得舒服又好看」。',
      expression: '数据看了，不焦虑——数据是好玩的，像跑步日记里随手记的一笔，不是打分。',
    },
    shareTagline: '全副武装的快乐跑者——装备满分，配速随缘',
  },

  // ═══ TYPE 18 · EGSP_A · 跑团策展人 ═══
  'EGSP_A': {
    typeId: 18,
    code: 'EGSP_A',
    name: '跑团策展人',
    emoji: '🦜',
    keywords: ['跑团气氛总导演', '荧光色终身代言人', '约跑=小型户外派对', '合影取景强迫症患者', '跑后聚餐铁杆发起人'],
    roast: '你是跑团的「全能甲方」——穿搭顾问、合影导演、气氛担当、跑后聚餐选址人，偶尔还客串「最后500米冲刺」喊话员。每次约跑前夜是你最忙的时候：挑衣服、搭配色、准备段子——比准备一场半马还投入。荧光粉上衣配彩虹袜、头顶发光发箍——你不是在追求性能，你是在追求「三百米外就能认出来」。跑到一半突然停下来说「这里光线好，来一张」——队友已经习惯了。跑步对你来说是载体，快乐才是本体。',
    traits: ['约跑前夜比准备比赛还忙', '荧光色上衣彩虹袜是标配', '跑到一半停下来拍照队友已习惯'],
    dimensionScores: { motivation: 1, social: 1, style: -1, ritual: -1, expression: 1 },
    color: '#e91e8f',
    colorFamily: 'forest',
    colorTone: 'bright',
    quote: '跑团真正的灵魂人物不是跑最快的那个——是穿最亮那个、笑最大声那个。',
    colorDark: '#ad1457',
    svgIcon: 'EGSA',
    animalEmoji: '🦜',
    animalName: '金刚鹦鹉',
    animalImg: '/runner-personality-h5/animals/animal-type-18.png',
    englishName: 'Macaw',
    hook: '跑团真正的灵魂人物不是跑最快的那个——是穿最亮那个、笑最大声那个。',
    dimensionComments: {
      motivation: '跑步的快乐=穿搭×合拍×段子×早午饭。配速？公式里最不重要的变量。',
      social: '跑团的灵魂人物——缺了你，约跑就是一群人在江边沉默地喘气。',
      style: '计划的重心永远是「怎么让大家更开心」——路线有风景、补给有惊喜、合影有创意。',
      ritual: '荧光色是信仰，彩虹袜是名片。你的装备不说话——但路人的回头率替你喊了。',
      expression: '每一次约跑都是你策展的一场户外派对——主题、视觉、流程、氛围，全是你的作品。',
    },
    shareTagline: '跑团首席快乐官——装备有多亮，人就有多暖',
  },

  // ═══ TYPE 19 · EGSS_D · 穿搭分析师 ═══
  'EGSS_D': {
    typeId: 19,
    code: 'EGSS_D',
    name: '穿搭分析师',
    emoji: '🦎',
    keywords: ['跑步OOTD分析师', '出片率导向穿搭', '配色系统架构师', '约跑=小型时装周', '赞数即KPI'],
    roast: '你的衣柜按跑步场景精准分区：晨跑系列、夜跑系列、雨天系列、比赛系列、约跑系列——分类比公司文件归档还清晰。每次约跑是你的小型装备发布会，出门前至少要试三套，最后选定还要拍照存档「今日跑步OOTD」。数据你也看——但不是配速数据，是「哪套穿搭获赞率最高」「哪种配色组合出片最稳」。你对新跑鞋的配色研究深度是性能研究的三倍——「这双荧光绿偏暖色，配冷色系压缩裤会打架」。',
    traits: ['衣柜按跑步场景精准分区', '出门前至少试三套跑步穿搭', '配色研究深度是性能研究的三倍'],
    dimensionScores: { motivation: 1, social: 1, style: 1, ritual: -1, expression: -1 },
    color: '#9b59b6',
    colorFamily: 'forest',
    colorTone: 'deep',
    quote: '别人赛前研究配速策略，你赛前研究的是——今天穿哪双袜子配哪件背心。',
    colorDark: '#7d3c98',
    svgIcon: 'EGSD',
    animalEmoji: '🦎',
    animalName: '变色龙',
    animalImg: '/runner-personality-h5/animals/animal-type-19.png',
    englishName: 'Chameleon',
    hook: '别人赛前研究配速策略，你赛前研究的是——今天穿哪双袜子配哪件背心。',
    dimensionComments: {
      motivation: '跑步=形式和内容的完美统一。形式（穿搭）做好了，内容（跑步）自然开心。',
      social: '约跑=你的穿搭周常发布会。你是跑团最认真的观众，也是最认真的参与者。',
      style: '跑步看心情——但穿搭从不随性。每一套都有配色逻辑和数据支撑。',
      ritual: '袜子颜色和上衣logo必须呼应——不是强迫症，是穿搭的基本修养。',
      expression: '你的数据维度是赞数、出片率、色彩搭配成功率。配速数据？那是附录。',
    },
    shareTagline: '跑团首席穿搭数据官——KPI是出片率，不是配速',
  },

  // ═══ TYPE 20 · EGSS_A · 穿搭艺术家 ═══
  'EGSS_A': {
    typeId: 20,
    code: 'EGSS_A',
    name: '穿搭艺术家',
    emoji: '🦋',
    keywords: ['跑步视觉总监', '配色主题发起人', 'OOTD型跑者', '跑步时装周终身VIP', '调色盘跑鞋墙'],
    roast: '跑步对你来说是一种带汗的时尚创作。每次约跑前你在镜子前面站的时间可能比跑步时间还长——不是纠结，是「既然要跑，就要跑成一幅画」。压缩裤是画布，跑鞋是画笔，跑步路线是你移动的画廊。你会根据天气、光线、季节定穿搭主题——春天叫「樱花粉」、夏天叫「薄荷绿」、秋天叫「落日橙」、冬天叫「雾霾蓝」。约完跑最重要的事不是拉伸——是发合照。你是跑团的视觉总监：调色、滤镜、拼图、配文，一条龙全包。',
    traits: ['每次约跑前镜前时间>跑步时间', '按季节定穿搭主题', '跑团视觉总监一条龙全包'],
    dimensionScores: { motivation: 1, social: 1, style: 1, ritual: -1, expression: 1 },
    color: '#e040fb',
    colorFamily: 'forest',
    colorTone: 'bright',
    quote: '你的跑鞋墙不是鞋柜——是一个调色盘，今天选哪一笔，决定了这次跑步的画风。',
    colorDark: '#7b1fa2',
    svgIcon: 'EGSA',
    animalEmoji: '🦋',
    animalName: '蝴蝶',
    animalImg: '/runner-personality-h5/animals/animal-type-20.png',
    englishName: 'Butterfly',
    hook: '你的跑鞋墙不是鞋柜——是一个调色盘，今天选哪一笔，决定了这次跑步的画风。',
    dimensionComments: {
      motivation: '跑步是审美的延伸——每一步都要好看，每一天都值得被看见。',
      social: '跑团视觉总监——合照你来拍、颜色你来调、配文你来写、九宫格你来排。',
      style: '跑步随性，穿搭精心——这种迷人的矛盾是你自洽的跑步美学。',
      ritual: '装备=调色盘。今天的配色决定了今天的心情、步频、甚至跑后配文的风格。',
      expression: '你不是在跑步，你是在用脚步进行「跑步生活方式」的全案创作。',
    },
    shareTagline: '跑得不一定最快——但一定穿得最美，拍得最好',
  },

  // ═══ TYPE 21 · EGLP_D · 精密独行侠 ═══
  'EGLP_D': {
    typeId: 21,
    code: 'EGLP_D',
    name: '精密独行侠',
    emoji: '🐱',
    keywords: ['独跑精密派', '一人份仪式感', '私密数据档案', '跑步品控师', '路线+配色+歌单三重奏'],
    roast: '你的跑步是一个人的精密工程。配色必须上下呼应、路线提前用街景地图踩过点、配速有自己的舒适区间——虽然那个区间宽松到「五分到七分都行」。你不跟跑团不是因为不合群——是因为你精心策划的路线、精确搭配的配色、精挑细选的歌单，没办法被一句随口的「今天跑哪」就打乱。你的装备购买决策像在写论文文献综述——参数对比、用户评测、实测分析，买一双鞋的准备时间比穿它的时间还长。数据是私密的日记，不给别人看，但每一条都认真存档——像在给未来的自己写信。',
    traits: ['路线提前踩点配色提前搭配歌单提前排好', '买鞋准备时间>穿鞋时间', '数据是给未来自己写的私密日记'],
    dimensionScores: { motivation: 1, social: -1, style: -1, ritual: -1, expression: -1 },
    color: '#6c5ce7',
    colorFamily: 'forest',
    colorTone: 'deep',
    quote: '一个人跑步不是孤独——是终于不用迁就任何人的节奏。',
    colorDark: '#4834d4',
    svgIcon: 'EGLD',
    animalEmoji: '🐱',
    animalName: '猫',
    animalImg: '/runner-personality-h5/animals/animal-type-21.png',
    englishName: 'Cat',
    hook: '一个人跑步不是孤独——是终于不用迁就任何人的节奏，连配速都精确到小数点后一位。',
    dimensionComments: {
      motivation: '跑步=给自己的一段高质量独处。精心准备，然后尽情享受。',
      social: '一个人的节奏最舒服——不需要等、不需要追、不需要聊、不需要解释。',
      style: '路线提前踩点、配色提前搭配、歌单提前排好——计划做足，跑起来才彻底放空。',
      ritual: '装备=精密仪器。每一件都经过参数对比和实测——买鞋比买股票还慎重。',
      expression: '数据是只写给自己看的日记——不晒、不分享，但每一条都在说「今天也不错」。',
    },
    shareTagline: '一个人的精密仪式——不需要观众，只需要自己满意',
  },

  // ═══ TYPE 22 · EGLP_A · 仪式感独行侠 ═══
  'EGLP_A': {
    typeId: 22,
    code: 'EGLP_A',
    name: '仪式感独行侠',
    emoji: '🦢',
    keywords: ['独处仪式感大师', '跑步自我约会', '路线审美学家', '一人份精致', '无需观众的独奏'],
    roast: '跑步是你一天中最精致的私人时光——准确地说，是你在跟自己约会。出门前装备配色必须在镜子前确认：上衣的蓝和鞋子的蓝是不是同一色号的蓝。歌单提前分阶段排好：头两公里轻音乐热身，中段切节奏跑，最后一公里切到最近循环的那首歌——高潮必须在冲线那一刻。路线也提前想好了：今天跑滨江，因为夕阳会在五点四十七分从那个桥洞穿过来，那一刻江水会变成碎金子。一个人的跑步不孤独——是一种饱满的自我陪伴。',
    traits: ['跑步是跟自己约会', '上衣和鞋子的蓝必须是同一个色号', '歌单分阶段编排高潮对准冲线'],
    dimensionScores: { motivation: 1, social: -1, style: -1, ritual: -1, expression: 1 },
    color: '#95a5a6',
    colorFamily: 'forest',
    colorTone: 'bright',
    quote: '一个人的跑步是一场给自己办的微型派对。',
    colorDark: '#7f8c8d',
    svgIcon: 'EGLA',
    animalEmoji: '🦢',
    animalName: '天鹅',
    animalImg: '/runner-personality-h5/animals/animal-type-22.png',
    englishName: 'Swan',
    hook: '一个人的跑步是一场给自己办的微型派对——配色、歌单、路线、心情，全是精心准备的礼物。',
    dimensionComments: {
      motivation: '跑步=给自己的礼物。每一步都在用心感受，每一帧都值得私藏回味。',
      social: '独处是最奢侈的享受。跑步是你跟自己的约会——不接受任何电灯泡。',
      style: '路线+歌单+配色=跑步三部曲。准备得越精心，跑起来越自由。',
      ritual: '配色不是为了出片——是为了取悦自己。上衣的蓝和鞋的蓝对上了，多巴胺就来了。',
      expression: '跑步是一场即兴的独奏会——你是唯一的演奏者和唯一的听众。刚好，你是最懂自己的那个听众。',
    },
    shareTagline: '一个人的精致奔跑——不需要观众，只需要自己心满意足',
  },

  // ═══ TYPE 23 · EGLS_D · 装备品鉴师 ═══
  'EGLS_D': {
    typeId: 23,
    code: 'EGLS_D',
    name: '装备品鉴师',
    emoji: '🐿️',
    keywords: ['跑鞋参数档案馆馆长', '三公里深度评测员', '中底回弹率收藏家', '鞋墙远大于跑量', '跑步的快乐=开箱+测评'],
    roast: '你是跑鞋界的活体数据库。跑量不大——但你对自己鞋柜里每一双鞋的了解程度，超过了品牌产品经理。中底回弹率、前后掌落差、鞋面透气指数、碳板刚性曲线——这些参数你随时可以报出来，像一个鞋圈首席分析师在报持仓。问题在于：买鞋的速度是消耗鞋的三倍。鞋柜里一半的鞋「上脚里程」不到二十公里，但它们各自的参数分析文档已经写了超过两千字。每次拆快递都像在验证一份参数报告——那种「终于摸到参数表里的鞋了」的满足感，比跑十公里还让你开心。',
    traits: ['鞋柜里一半鞋上脚不到二十公里', '每双鞋的参数分析文档超两千字', '拆快递的满足感>跑十公里'],
    dimensionScores: { motivation: 1, social: -1, style: 1, ritual: -1, expression: -1 },
    color: '#e74c3c',
    colorFamily: 'forest',
    colorTone: 'deep',
    quote: '月跑量五十公里，鞋墙已经建到第三层。',
    colorDark: '#c0392b',
    svgIcon: 'EGLD',
    animalEmoji: '🐿️',
    animalName: '松鼠',
    animalImg: '/runner-personality-h5/animals/animal-type-23.png',
    englishName: 'Squirrel',
    hook: '月跑量五十公里，鞋墙已经建到第三层——每一双都有详细参数档案，但大部分只上脚跑了三公里。',
    dimensionComments: {
      motivation: '跑步的快乐分裂了——一半在跑，一半在研究和买。但两个都让你快乐。',
      social: '一个人买、一个人测、一个人存档——你的跑鞋实验室不需要助手，只需要快递小哥。',
      style: '今天跑不跑看心情——但今天研究哪位博主的新鞋评测是固定日程。',
      ritual: '跑鞋数据库管理员——参数、实测、退役评估，比品牌官网还详细。跑不跑不重要，先买了再说。',
      expression: '你的数据不是配速——是回弹率、落差、透气性。你的数据分析维度比别人多五个。',
    },
    shareTagline: '跑鞋评测数据库——跑量不大，但研究深度无人能及',
  },

  // ═══ TYPE 24 · EGLS_A · 审美漫游者 ═══
  'EGLS_A': {
    typeId: 24,
    code: 'EGLS_A',
    name: '审美漫游者',
    emoji: '🦩',
    keywords: ['跑步审美学家', '光影猎人', '五公里出片王', '颜值即正义跑者', '路线的审美标准比配速标准还高'],
    roast: '你是跑圈的另一条赛道：审美赛道。装备的第一KPI不是性能——是颜值。丑的鞋哪怕回弹率百分之九十也进不了你的鞋柜。一个人跑，因为没人能理解你为什么停下来拍了五分钟的树——或者蹲在路边等了十分钟，就为了等一个路人走进你的构图。没有训练计划——今天跑三公里还是十公里，取决于沿途有多少「值得停下来」的东西。你的跑步路线必须满足审美标准：江边落日路线、林荫道光影路线、老城区涂鸦墙路线——配速？跟上沿途风景变换的节奏就行。',
    traits: ['丑的鞋回弹率90%也不买', '停下来拍树五分钟等路人十分钟', '路线根据审美标准选择'],
    dimensionScores: { motivation: 1, social: -1, style: 1, ritual: -1, expression: 1 },
    color: '#e91e8f',
    colorFamily: 'forest',
    colorTone: 'bright',
    quote: '穿最贵的鞋跑最佛的步，停下来的理由不是累了——是光太美。',
    colorDark: '#ad1457',
    svgIcon: 'EGLA',
    animalEmoji: '🦩',
    animalName: '火烈鸟',
    animalImg: '/runner-personality-h5/animals/animal-type-24.png',
    englishName: 'Flamingo',
    hook: '穿最贵的鞋跑最佛的步，停下来的理由不是累了——是「刚才那束光穿过树叶的角度太绝了」。',
    dimensionComments: {
      motivation: '跑步=审美散步。每一帧画面都比每一步配速重要——出汗只是顺便。',
      social: '一个人的审美之旅没有固定班次——等人会打断你的构图和节奏感。',
      style: '没有训练计划——但有一条动态审美路线。阳光好就跑远的那条，阴天就跑近的那条。',
      ritual: '装备第一KPI=颜值。性能够用就行——但不够好看的鞋根本不配被买回来。',
      expression: '你不是在跑步，你是在用脚步进行「城市美学考察」。呼吸只是节拍器。',
    },
    shareTagline: '跑得不多——但每一步都值得被拍下来',
  },

  // ═══ TYPE 25 · EMSP_D · 数据稳定流 ═══
  'EMSP_D': {
    typeId: 25,
    code: 'EMSP_D',
    name: '数据稳定流',
    emoji: '🐢',
    keywords: ['数据禅', '全勤奖终身成就', '同款鞋收藏家', 'PB免疫体质', '佛系理科生'],
    roast: '这类跑者有一种令人羡慕的稳定气质。他们的跑量曲线平滑得像Excel里拉出来的趋势线，配速方差小到让强迫症患者极度舒适。但你永远不会看到他们为了刷PB把自己跑崩——对数据的关注止于「了解」，绝不滑向「焦虑」。装备精简到极致，一双鞋跑到退役才换同款，GPS手表用了三年屏幕都花了也不换——因为够用。他们是跑团里最靠谱的存在，说周二跑绝不周三跑，出勤率让团长感动得想给发全勤奖。他们对跑步的理解已经超越了「卷」和「躺」的二元对立，进入了一种数据时代的禅意——知道自己的数字，但不被数字定义。',
    traits: ['跑量曲线平滑得像Excel趋势线', '一双鞋穿到退役才换同款', '知道自己的数字但不被数字定义'],
    dimensionScores: { motivation: 1, social: 1, style: -1, ritual: 1, expression: -1 },
    color: '#2ecc71',
    colorFamily: 'forest',
    colorTone: 'deep',
    quote: '手表是副驾，不是老板。数据好看就够了，不用更好看。',
    colorDark: '#27ae60',
    svgIcon: 'EMSD',
    animalEmoji: '🐢',
    animalName: '乌龟',
    animalImg: '/runner-personality-h5/animals/animal-type-25.png',
    englishName: 'Tortoise',
    hook: '手表是副驾，不是老板。数据好看就够了，不用更好看。',
    dimensionComments: {
      motivation: '一双鞋穿到磨平花纹，同款补货，不问新款。',
      social: '跑团全勤王，来了就跑，跑完就走，话不多。',
      style: '周计划像铁轨，跑不跑只看天气，不看心情。',
      ritual: '手表数据是用来「知道」的，不是用来「比较」的。',
      expression: 'PB随缘，稳定的幸福感比数字的突破更重要。',
    },
    shareTagline: '跑得稳，比跑得快更难。',
  },

  // ═══ TYPE 26 · EMSP_A · 朴素陪伴者 ═══
  'EMSP_A': {
    typeId: 26,
    code: 'EMSP_A',
    name: '朴素陪伴者',
    emoji: '🐕',
    keywords: ['约跑永动机', '跑团粘合剂', '装备极简到犯罪', '社交型跑者', '跑完那顿才是正餐'],
    roast: '这类跑者的装备可能是跑团最随意的——鞋子是两年前双十一凑单买的，衣服是公司发的团建T恤，但你约他跑步，他永远准时。不是因为热爱跑步，是因为热爱跟你们在一起的那一小时。跑得快跑得慢无所谓，重要的是跑完一起去喝豆浆时聊的那十分钟八卦。他们的跑步动机纯粹到令人感动：不是减肥、不是健康、不是PB，就是「你在群里@我了，那我得来」。他们是跑团的粘合剂——没有他们，跑团就只剩下一群对着手表较劲的沉默跑者。',
    traits: ['装备是两年前双十一凑单买的', '跑步动机=你在群里@我了', '跑完喝豆浆聊八卦才是正事'],
    dimensionScores: { motivation: 1, social: 1, style: -1, ritual: 1, expression: 1 },
    color: '#f39c12',
    colorFamily: 'forest',
    colorTone: 'bright',
    quote: '跑步是借口，跟你们待在一起才是正事。',
    colorDark: '#d68910',
    svgIcon: 'EMSA',
    animalEmoji: '🐕',
    animalName: '金毛犬',
    animalImg: '/runner-personality-h5/animals/animal-type-26.png',
    englishName: 'Golden Retriever',
    hook: '跑步是借口，跟你们待在一起才是正事。',
    dimensionComments: {
      motivation: '最贵的装备是跑完请喝的奶茶，鞋是凑单买的。',
      social: '跑团灵魂人物，不跑步也会来场边递水聊天。',
      style: '没有训练计划，只有约跑日历——有人约就出动。',
      ritual: '手表只用来收微信，数据页面从来没切过。',
      expression: '今天的KPI是「大家都笑了」，已完成。',
    },
    shareTagline: '人不鸽，就是最好的配速。',
  },

  // ═══ TYPE 27 · EMSS_D · 随缘数据派 ═══
  'EMSS_D': {
    typeId: 27,
    code: 'EMSS_D',
    name: '随缘数据派',
    emoji: '🐨',
    keywords: ['薛定谔的训练计划', '被@必到', '佛系数据党', '跑量感人但GPS全开', '碎片化跑步艺术家'],
    roast: '这是跑圈最矛盾又最真实的物种。嘴上说「今天太累了不跑了」，群里有人喊一声立马换鞋出门；嘴上说「数据不重要随便跑跑」，跑完第一件事就是翻配速页面。他们不会主动组织跑步，但被@到的响应率接近100%。他们的训练计划是一张薛定谔的白纸——你不问就没有，你一问可能明天就有了。他们对数据的态度像刷朋友圈：不刻意，但时不时就想点开看一眼。一个月跑量可能只有50公里，但每一公里都有GPS记录，精确到秒。这种随缘但不随便的态度，构成了跑圈最松弛的中间态。',
    traits: ['嘴上说不跑群里一喊就出门', '跑完第一件事翻配速页面', '月跑量50K但每公里GPS全开'],
    dimensionScores: { motivation: 1, social: 1, style: 1, ritual: 1, expression: -1 },
    color: '#1abc9c',
    colorFamily: 'forest',
    colorTone: 'deep',
    quote: '跑不跑看缘分，但跑了一定要开表。',
    colorDark: '#16a085',
    svgIcon: 'EMSD',
    animalEmoji: '🐨',
    animalName: '考拉',
    animalImg: '/runner-personality-h5/animals/animal-type-27.png',
    englishName: 'Koala',
    hook: '跑不跑看缘分，但跑了一定要开表。',
    dimensionComments: {
      motivation: '手表一定要有GPS，虽然一个月只跑几次。',
      social: '群里潜水冠军，但被@后30秒内回复「几点？」',
      style: '训练计划？看群公告。群没公告？那今天休息。',
      ritual: '跑量不大但数据齐全，每一公里都被认真归档。',
      expression: '月跑量目标定得很低，完成了就很开心。',
    },
    shareTagline: '佛系跑步，严谨记录。',
  },

  // ═══ TYPE 28 · EMSS_A · 松弛代言人 ═══
  'EMSS_A': {
    typeId: 28,
    code: 'EMSS_A',
    name: '松弛代言人',
    emoji: '🦫',
    keywords: ['怎么都行', '跑休零焦虑', '团服文案供应商', '手表忘开专业户', '松弛界天花板'],
    roast: '这类跑者是跑圈的松弛感天花板。当别人在纠结今天跑间歇还是节奏跑时，他们还在纠结要不要换鞋。当别人在手表上设置配速提醒时，他们的手表可能在包里根本没戴。他们跑步只有一个原则：不勉强。快了就慢点，累了就少跑两公里，风景好就停下来拍个照。他们永远不会患上「跑休焦虑症」，因为不跑的那天他们也很开心——可以多睡半小时。跑团里最需要这样的人：当所有人都卷起来的时候，他们一句「差不多得了」能把整个跑团的血压降下来。',
    traits: ['跑步只有一个原则：不勉强', '手表经常忘在包里没戴', '一句差不多得了降低全团血压'],
    dimensionScores: { motivation: 1, social: 1, style: 1, ritual: 1, expression: 1 },
    color: '#f1c40f',
    colorFamily: 'forest',
    colorTone: 'bright',
    quote: '来都来了、跑都跑了、快慢都行——这八个字刻团服上够了。',
    colorDark: '#d4ac0d',
    svgIcon: 'EMSA',
    animalEmoji: '🦫',
    animalName: '水豚',
    animalImg: '/runner-personality-h5/animals/animal-type-28.png',
    englishName: 'Capybara',
    hook: '来都来了、跑都跑了、快慢都行——这八个字刻团服上够了。',
    dimensionComments: {
      motivation: '穿什么跑取决于昨天洗了什么，没洗就继续穿。',
      social: '群里最常说「我都行」的那个人，是真的都行。',
      style: '计划就是「看心情」，心情好的时候可以跑远一点。',
      ritual: '手表经常忘开，跑完才发现——「哦，那就算没跑吧。」',
      expression: '今日目标：出门了。今日成就：已超额完成。',
    },
    shareTagline: '松弛，是最好的跑姿。',
  },

  // ═══ TYPE 29 · EMLP_D · 身体翻译官 ═══
  'EMLP_D': {
    typeId: 29,
    code: 'EMLP_D',
    name: '身体翻译官',
    emoji: '🦇',
    keywords: ['人体数据科学家', '同路偏执狂', '心率读心术', '跑步版长期跟踪', '自我量化先驱'],
    roast: '这类跑者有一种近乎偏执的稳定。同一条路线，同一个时间，同一双鞋，跑了三年。在外人看来这简直是行为艺术，但他们知道自己在做什么：把变量控制到最少，才能听清身体的每一个信号。今天比昨天慢了5秒——不是状态下滑，是昨晚睡晚了半小时。心率比平时高了3跳——不是体能问题，是下午那杯咖啡。他们已经把自己的身体跑成了一本打开的书，每一个数据波动都是一个清晰的句子。他们对跑步的追求不是更快更远，而是更了解自己。',
    traits: ['同一条路线同一个时间同一双鞋跑三年', '每一个数据波动都能解释原因', '追求更了解自己而非更快更远'],
    dimensionScores: { motivation: 1, social: -1, style: -1, ritual: 1, expression: -1 },
    color: '#2c3e80',
    colorFamily: 'forest',
    colorTone: 'deep',
    quote: '同一条路跑三年，不是为了数据，是为了读懂自己。',
    colorDark: '#1a237e',
    svgIcon: 'EMLD',
    animalEmoji: '🦇',
    animalName: '蝙蝠',
    animalImg: '/runner-personality-h5/animals/animal-type-29.png',
    englishName: 'Bat',
    hook: '同一条路跑三年，不是为了数据，是为了读懂自己。',
    dimensionComments: {
      motivation: '一双鞋穿三年，鞋底的磨损曲线比体检报告还准。',
      social: '一个人跑，不约不组，独处是最好的数据采集环境。',
      style: '每天同一条路线，不是路径依赖，是控制变量。',
      ritual: '心率多跳一下都能察觉，身体被量化成了仪表盘。',
      expression: 'PB不是数字的突破，是比昨天多读懂了一个身体信号。',
    },
    shareTagline: '跑三年同一条路，为了听懂自己。',
  },

  // ═══ TYPE 30 · EMLP_A · 都市隐修士 ═══
  'EMLP_A': {
    typeId: 30,
    code: 'EMLP_A',
    name: '都市隐修士',
    emoji: '🦢',
    keywords: ['都市苦行僧', '同一条路钉子户', '移动冥想者', '路灯编号专家', '梧桐物候学'],
    roast: '都市里有一种跑者，他们的跑步路线图打开来是一条粗到发黑的线——因为三年跑了同一段路几百次。不是不知道别的地方有更好的风景，是他们根本不需要「更好」。这条路刚好够长，够安静，够他们想清楚今天要处理的事情、捋清楚最近的情绪。跑完一圈，心里的事也跑顺了。他们是跑步界的隐修士——不需要远行，不需要变换，在重复中找到深度。别人在讨论哪条赛道风景好，他们在同一条路边观察季节的变化：梧桐什么时候开始落叶，路灯什么时候换了新灯泡。',
    traits: ['路线图是一条粗到发黑的线', '在同一条路边观察季节变化', '不需要更好因为重复中能找到深度'],
    dimensionScores: { motivation: 1, social: -1, style: -1, ritual: 1, expression: 1 },
    color: '#95a5a6',
    colorFamily: 'forest',
    colorTone: 'bright',
    quote: '跑了三年同一条路——不是没选择，是选择了不选。',
    colorDark: '#7f8c8d',
    svgIcon: 'EMLA',
    animalEmoji: '🦢',
    animalName: '白鹭',
    animalImg: '/runner-personality-h5/animals/animal-type-30.png',
    englishName: 'Egret',
    hook: '跑了三年同一条路——不是没选择，是选择了不选。',
    dimensionComments: {
      motivation: '鞋子不求新，求的是每一步落地都像老朋友打招呼。',
      social: '独跑是充电，约跑是放电——电量有限，节省着用。',
      style: '没有计划就是最好的计划，路线固定，心是自由的。',
      ritual: '不看手表看天色，跑完看的是自己有没有更平静。',
      expression: '跑完想通一件事，比跑完刷一个PB更有成就感。',
    },
    shareTagline: '重复，是最深的自由。',
  },

  // ═══ TYPE 31 · EMLS_D · 轨迹涂鸦者 ═══
  'EMLS_D': {
    typeId: 31,
    code: 'EMLS_D',
    name: '轨迹涂鸦者',
    emoji: '🐙',
    keywords: ['GPS涂鸦艺术家', '红绿灯导航系统', '路线抽象派', '缺腿兔子创作者', '城市即兴画师'],
    roast: '这类跑者出门前从不知道要去哪儿。左转还是右转，取决于哪个方向的红绿灯先变绿。但他们有一个雷打不动的习惯：跑完一定打开地图，欣赏今天即兴创作的GPS涂鸦。有时候是一条歪歪扭扭的蛇，有时候是一只缺了腿的兔子，偶尔人品爆发画出一颗心——能开心一整天。他们对跑步路线的态度像街头艺术家对待一面墙：空白就值得画点什么，画成什么样不重要，重要的是画了。别人在追求配速的时候，他们在追求路线的几何美学。今天这条线太直了没意思，明天要故意拐几个弯。',
    traits: ['出门方向由红绿灯决定', '跑完一定打开地图欣赏GPS涂鸦', '追求路线几何美学而非配速'],
    dimensionScores: { motivation: 1, social: -1, style: 1, ritual: 1, expression: -1 },
    color: '#e67e22',
    colorFamily: 'forest',
    colorTone: 'deep',
    quote: '没有路线规划，但跑完一定会看地图——今天画了个什么？',
    colorDark: '#d35400',
    svgIcon: 'EMLD',
    animalEmoji: '🐙',
    animalName: '章鱼',
    animalImg: '/runner-personality-h5/animals/animal-type-31.png',
    englishName: 'Octopus',
    hook: '没有路线规划，但跑完一定会看地图——今天画了个什么？',
    dimensionComments: {
      motivation: '手表必须有GPS，不是为了配速，是为了生成画布。',
      social: '偶尔约跑，但会提前声明：我路线很随机的，跟丢不负责。',
      style: '出门方向由红绿灯决定，跑完形状由运气决定。',
      ritual: '配速不重要，重要的是今天的地图截图能不能发朋友圈。',
      expression: '有生之年跑出一只完整的动物，目前最好成绩是缺腿兔子。',
    },
    shareTagline: '用脚丫子画地图。',
  },

  // ═══ TYPE 32 · EMLS_A · 自由流浪者 ═══
  'EMLS_A': {
    typeId: 32,
    code: 'EMLS_A',
    name: '自由流浪者',
    emoji: '🕊️',
    keywords: ['城市游牧族', '路口决策困难户', '跑步即兴派', '数据免疫者', '完全自由人'],
    roast: '这类跑者的人生信条可以用四个字概括：跑就完了。没有训练计划、没有配速目标、没有固定路线——甚至连跑多久都是跑到不想跑为止。他们是跑圈真正的自由派，跑步对他们来说不是任务不是习惯，是一种冲动。今天看到窗外天气好，换鞋出门；今天加班太累，不跑也很坦然。他们跑步时最大的消耗不是体力，是决定在每个路口左转还是右转的脑力。风往哪边吹就往哪边跑，哪条巷子没走过就往哪钻。不需要终点，因为过程本身就是目的。不需要记录，因为感受不需要被量化。',
    traits: ['跑到不想跑为止', '风往哪边吹就往哪边跑', '过程本身就是目的不需要记录'],
    dimensionScores: { motivation: 1, social: -1, style: 1, ritual: 1, expression: 1 },
    color: '#3498db',
    colorFamily: 'forest',
    colorTone: 'bright',
    quote: '不确定去哪儿，不确定跑多久——确定的是跑起来就对了。',
    colorDark: '#2980b9',
    svgIcon: 'EMLA',
    animalEmoji: '🕊️',
    animalName: '信天翁',
    animalImg: '/runner-personality-h5/animals/animal-type-32.png',
    englishName: 'Albatross',
    hook: '不确定去哪儿，不确定跑多久——确定的是跑起来就对了。',
    dimensionComments: {
      motivation: '脚上有鞋就能跑，没有鞋光脚也不是不行。',
      social: '不约跑，但路上遇到了可以并行一段，然后自然分叉。',
      style: '计划就是「想跑就跑」，不想跑的借口也很充分。',
      ritual: '不记录，不分享，跑过就是跑过，不需要证据。',
      expression: '没有目标。跑步本身就是奖励，不需要额外奖赏。',
    },
    shareTagline: '风在哪，就往哪跑。',
  },
};

/** 按 typeId 索引的人格查找表 */
const byTypeId: Record<PersonalityTypeId, PersonalityResult> = {} as any;
for (const p of Object.values(personalityData)) {
  byTypeId[p.typeId] = p;
}

/** 按编码获取人格 */
export function getPersonality(code: PersonalityCode): PersonalityResult | undefined {
  return personalityData[code];
}

/** 按 typeId 获取人格 */
export function getPersonalityByTypeId(typeId: PersonalityTypeId): PersonalityResult {
  return byTypeId[typeId];
}

/** 获取全部 32 型人格 */
export function getAllPersonalities(): PersonalityResult[] {
  return Object.values(personalityData);
}
